apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system # 1
  labels:
    k8s-app: fluentd-logging # 2
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  updateStrategy:
    type: RollingUpdate # 3
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
    spec:
      containers:
        - name: fluentd-elasticsearch
          image: quay.io/fluentd_elasticsearch/fluentd:v2.5.2 # 4
          env:
            - name: testenv
              value: value
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi