# 빌드 스테이지
# FROM golang:1.17 AS builder
# WORKDIR /app
# COPY main.go .
# RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# 최종 스테이지
FROM busybox:latest
WORKDIR /root/
# COPY --from=builder /app/main .
COPY main .
CMD ["/bin/sh"]
